// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";
import { fileURLToPath } from "node:url";
import path from "node:path";

const academyRoot = fileURLToPath(new URL(".", import.meta.url));
dotenv.config({ path: path.join(academyRoot, ".env.migrate.local"), override: true });
dotenv.config({ path: path.join(academyRoot, ".env.local") });
dotenv.config({ path: path.join(academyRoot, ".env") });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Use a direct connection for Prisma CLI workflows when available.
    url: process.env["ACADEMY_TEST_DATABASE_URL"] ?? process.env["ACADEMY_DIRECT_DATABASE_URL"] ?? process.env["ACADEMY_DATABASE_URL"],
  },
});
